### ISSUE TITLE
Setup Lead Matching - review and transition to Pages site

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community-Sprints/summit-events-app-documentation#7] opened 2022-04-14 14:37 UTC
Review documentation for accuracy and transition to new Pages site.
https://github.com/SFDO-Community/Summit-Events-App/wiki/0c-%E2%80%93-Setup-Lead-Matching

Added to the bottom of the Contact Matching page.  Will rework later: https://github.com/SFDO-Community-Sprints/summit-events-app-documentation/blob/main/docs/advanced-features/contact-and-lead-matching.md

**Comment by rdblake21** [comment] 2023-09-29 18:06
Closing at this is is a duplicate of #45 

Duplicate #45

**Closed by rdblake21** 2023-09-29 18:06 UTC
